# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: CmdLine@2
  inputs:
    script: 'dir'
    workingDirectory: '/home/vsts/work/1/s/'
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: '/sp-ckeditor4.16.2'
    publishRegistry: 'useFeed'
    publishFeed: '86ec7889-a365-4cd1-90df-6e18cc2ea59f'